dart-lang/html

lib/src/encoding_parser.dart, test/parser_feature_test.dart
Caught this while investigating an unused local. In Python, the iterator would advance, but in the ported code it was not.
=> Fixes encoding parser to handle whitespace correctly.

.gitignore, CHANGELOG.md, lib/dom.dart
This package can't run with the --preview-dart-2 flag currently (and is a transitive dependency of other tools like the analyzer, which also can't run in preview dart 2 as a result). Here's the failure:
```
lib/dom.dart:972:15: Error: Can't infer the type of 'element': overridden members must all have the same type.
Specify the type explicitly.
int indexOf(element, [int start = 0]) => _filtered.indexOf(element, start);
^
lib/dom.dart:976:19: Error: Can't infer the type of 'element': overridden members must all have the same type.
Specify the type explicitly.
int lastIndexOf(element, [int start]) {
^
```
=> fix an issue when run with --preview-dart-2

test/parser_feature_test.dart
Version `1.5.0` of `source_span` changed the output format. Update the
tests which hardcoded the expected output to the new format.
=> Update test expectations for source_span output

.travis.yml, CHANGELOG.md, lib/src/constants.dart, pubspec.yaml
If folks have not upgraded to the latest pkg:html, they should still
be able to get the latest pkg:csslib
(This is particularly important since there is a pkg:analyzer dependency
here that moves slowly.)
=> Support the latest pkg:csslib on the 0.13 version path

.travis.yml, CHANGELOG.md, lib/src/html_input_stream.dart, pubspec.yaml, test/data/tokenizer/unicodeCharsSurrogates.test, test/tokenizer_test.dart
This CL fixes the issue described in https://github.com/dart-lang/html/issues/70.
'runes' are being used to return chars, but index positions are expressed in 'codeUnits'. When a unicode with a surrogate is encountered (eg. an emoji), 1 rune is used to express 2 code units.
=> Fix spans generated for HTML with higher-plane unicode characters

.travis.yml, lib/src/constants.dart, lib/src/tokenizer.dart, lib/src/utils.dart
- Drop the `Predicate` typedef, it is unused.
- Remove `parseIntRadix`, replace with `int.parse`.
- Remove unnecessary `library` directives and a comment that added no
information.
- Drop unused constants.
- Simplify `startsWithAny`.
- Remove an ignore that was working around an analyzer bug which no
longer exists.
=> Refactor some utilities

CHANGELOG.md, lib/parser.dart, pubspec.yaml, test/data/tree-construction/regression_tests.dat
Closes #122
Add 'button' to the tags that are processed with `endTagBlock`. The spec
at https://html.spec.whatwg.org/multipage/parsing.html includes 'button'
in the list of end tags with this treatment.
Add a new `.dat` file for regression test. It include an `#info` field
which is new but can be parsed safely to mark the issue for which it is
a test. This test loops endlessly before the fix and passes after the
fix.
Note that since errors are currently untested and tests fail if they are
tested the error will be left without content for now.
=> Fix infinite loop with bad button close tag

CHANGELOG.md, analysis_options.yaml, lib/dom.dart, lib/dom_parsing.dart, lib/parser.dart, lib/src/query_selector.dart, lib/src/token.dart, lib/src/tokenizer.dart, lib/src/treebuilder.dart, lib/src/utils.dart, pubspec.yaml, test/parser_feature_test.dart, test/parser_test.dart, test/selectors/level1_lib.dart, test/support.dart, test/tokenizer_test.dart
This will make it easier to migrate to null safety which also disables
implicit casts except from dynamic. Also fix the implicit casts from
dynamic since this package has a lot of dynamic code that is harder to
read with implicit casts.
- Add argument types to some signatures that should have had them from
the start.
- Add explicit casts.
- Extract a few new local variables to make some of the casts only need
to happen once.
- Use `Iterable.whereType` in a loop instead of a type check and
`continue` in the loop body.
=> Disable implicit casts

analysis_options.yaml, lib/dom.dart, lib/dom_parsing.dart, lib/parser.dart, lib/src/constants.dart, lib/src/css_class_set.dart, lib/src/encoding_parser.dart, lib/src/html_input_stream.dart, lib/src/query_selector.dart, lib/src/tokenizer.dart, lib/src/treebuilder.dart, lib/src/utils.dart, test/dom_test.dart, test/parser_feature_test.dart, test/parser_test.dart, test/selectors/level1_baseline_test.dart, test/selectors/level1_lib.dart, test/support.dart, test/tokenizer_test.dart
This package has a number of long methods as well as patterns where the
reassignment to local variables is a critical detail. Make it easier to
work with by marking locals that don't change with `final`.
=> Enable and fix lint prefer_final_locals

.travis.yml, lib/parser.dart, lib/src/constants.dart, lib/src/tokenizer.dart, pubspec.yaml
- Switch to an extension method which will work nicer with `?.` instead
of needing to handle a null argument and has nicer looking usage.
- Rename to `toAsciiLowerCase` for consistency with the similar method
in the SDK.
- Use `Iterable.map` to avoid needing to create a fixed size list which
will not work well with the null safety migration.
This method is an internal detail and this is not breaking.
=> Rewrite asciiUpper2Lower as an extension

lib/src/html_input_stream.dart
The usage of this field was removed in
https://github.com/dart-lang/html/commit/eaca2abbf149ab4d280ae94cb6e67480db421c0e
=> Remove unused field _lineStarts

lib/dom.dart, lib/parser.dart, lib/src/token.dart, test/parser_feature_test.dart
Replace fields and Map keys with `Object` where they were previously
`dynamic`.
=> Use Object in place of dynamic

lib/parser.dart, lib/src/treebuilder.dart
The checks against `== Marker` won't upgrade a nullable variable to
non-nullable like `== null` would.
- Replace `Marker` with `null`. Remove the field.
- Add a doc comment on the class to link to the parsing spec and
describe the usage of `null`.
- Add a doc comment on `add` to describe it's difference from the normal
`List.add`.
- Add some comments and a link to an issue filed about a likely bug in
this method.
=> Remove Marker as a name for null

CHANGELOG.md, lib/parser.dart
These fields are unused in both this library and the python library from
which it was transliterated. The `lastPhase` was later named to
`originalPhase` but not all references were cleaned up which leaves one
remaining assignment to null. `beforeRcDataPhase` was unused in the
commit which introduced it and never assigned an interesting value or
read the field.
=> Drop unused lastPhase and beforeRcDataPhase fields

test/support.dart
The dart idiom for a repeated string is `operator *`. Remove an
unnecessary intermediate list and `String.fromCharCodes`.
=> Remove a fixed size list creation

lib/src/html_input_stream.dart
When we know the length to be 1, use `String.fromCharCode` instead of
`String.fromCharCodes`.
=> Avoid extra list for single character strings

analysis_options.yaml, lib/dom.dart, lib/parser.dart, lib/src/constants.dart, lib/src/html_input_stream.dart, lib/src/token.dart
Fix some typos and reference to deleted or renamed members. Rephrase
some docs that were not following best practices.
=> Enable and fix lint comment_references

test/parser_test.dart, test/selectors/level1_baseline_test.dart, test/support.dart, test/tokenizer_test.dart
In Dart 2.12 the `Platform.packageConfig` changes from `.packages` to
`.dart_tool/package_config.json` which causes the data file discovery to
fail. Switch to resolving a `package:html` URI and assuming the pub
package layout which is more reliable and stable than the package config
file location.
- Migrate from `Platform.packageConfig` to `Isolate.resolvePackageUri`.
- Change the utility methods to be asynchronous and update the `main`
for tests to `async`.
- Rename from `testDir` to `testDirectory`.
- Rename methods away from `get*`
=> Find test data files from package: URI

CHANGELOG.md, lib/dom_parsing.dart, lib/html_escape.dart
This allows build targets to use `htmlSerializeEscape` without bringing in any of `package:html`'s deps.
=> Move htmlSerializeEscape into its own library

analysis_options.yaml
These are a long outdated legacy pattern which brought external CI more
inline with internal standards where these errors would fail the build.
We are now more strict and the upgrades only impact local development
where they are not useful.
=> Drop unnecessary severity upgrades

CHANGELOG.md, analysis_options.yaml, lib/dom.dart, lib/dom_parsing.dart, lib/parser.dart, lib/src/encoding_parser.dart, lib/src/tokenizer.dart, lib/src/treebuilder.dart, test/tokenizer_test.dart
I think these are all related, but I'm happy to split up if desirable.
dartdoc is one of the heavy users of package:html, and we'd like it to be as performant as possible. This change _seems_ to have reduced dartdoc's memory consumption by ~2%, but that could be within the margin of error.
Changes include:
* Use `growable: false` where possible.
* Add type annotations to empty Lists, so they're not `List<dynamic>` (need to enable `strict-raw-types`).
* Flip from `implicit-casts: false` to `strict-casts: true`.
* Replace `List.from` with `List.of`.
* Cast `dynamic` things to `List` before iterating over them in a for loop.
=> Use growable lists and avoid dynamic

.github/workflows/test-package.yml, CHANGELOG.md, analysis_options.yaml, lib/parser.dart, lib/src/constants.dart, lib/src/html_input_stream.dart, lib/src/list_proxy.dart, lib/src/query_selector.dart, lib/src/token.dart, lib/src/tokenizer.dart, lib/src/treebuilder.dart, lib/src/utils.dart, pubspec.yaml, test/parser_test.dart, test/selectors/level1_baseline_test.dart, test/selectors/level1_lib.dart, test/selectors/selectors.dart, test/support.dart, test/tokenizer_test.dart
- finish the work to remove dynamic calls (fix https://github.com/dart-lang/html/issues/173)
- reduce use of dynamic generally; add additional types at the API boundary
- update to `package:lints` 2.0
- rev to `0.15.2-dev` (there are some other things I'd like to land before a publish)
=> finish work for avoid_dynamic_calls

lib/dom.dart
These are private definitions and are only ever used in a `with` clause. They should just be changed to `mixin` to become compatible with Dart language 3.0.
=> Dart 3 compatibility: turn classes into mixins

.github/workflows/test-package.yml, CHANGELOG.md, lib/src/css_class_set.dart, lib/src/tokenizer.dart, pubspec.yaml, test/query_selector_test.dart
- Widen the dependency on `package:csslib`.
- prep for publishing
---
<details>
<summary>Contribution guidelines:</summary><br>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note …
=> widen the dependency on 'package:csslib'

lib/parser.dart, lib/src/html_input_stream.dart, lib/src/list_proxy.dart
Update comments that set off a false positive in the
`unintended_html_in_doc_comment` lint. For references to core Dart
types with generics, replace the square braces with backticks since it
isn't useful to constantly link them.
For the comments that are edited, and a few nearby, update for style:
- Separate out a header as it's own paragraph.
- Reduce repetitive phrasing and redundant links to the same arguments.
Use a trailing comma for a long argument list, and re-order the
arguments so that the always-useful arguments are at the top, and the
arguments only pertaining to certain uses follow.
=> Fix doc comments
